"""Protocol and runtime constants shared across the server."""

from __future__ import annotations

SYMBOLIZER_FINALIZE_MARGIN_SECONDS = 5

HEADER_SCHEMA_VERSION = "X-APM-Schema-Version"
HEADER_APP_ID = "X-APM-App-Id"
HEADER_ENVIRONMENT = "X-APM-Environment"
HEADER_SDK_VERSION = "X-APM-SDK-Version"
HEADER_APP_VERSION = "X-APM-App-Version"
HEADER_APP_BUILD = "X-APM-App-Build"
HEADER_BATCH_ID = "X-Apm-Batch-Id"
HEADER_EVENT_COUNT = "X-Apm-Event-Count"
HEADER_VERSION_CODE = "X-APM-Version-Code"
HEADER_VARIANT = "X-APM-Variant"
HEADER_ABI = "X-APM-ABI"
HEADER_BUILD_ID = "X-APM-Build-Id"
HEADER_CHECKSUM_SHA256 = "X-APM-Checksum-SHA256"
HEADER_REQUEST_ID = "X-Request-Id"
HEADER_INSTALLATION_ID = "X-APM-Installation-Id"

SCHEMA_VERSION_V1 = "1"
SCHEMA_VERSION_V2 = "2"
SCHEMA_VERSION_V3 = "3"
SUPPORTED_SCHEMA_VERSIONS = frozenset({SCHEMA_VERSION_V1, SCHEMA_VERSION_V2, SCHEMA_VERSION_V3})

LINE_CONTENT_TYPE = "text/plain"
PROTOBUF_CONTENT_TYPE = "application/x-protobuf"
PROTOBUF_ENVELOPE_V2_CONTENT_TYPE = "application/x-protobuf; message=ApmBatchEnvelope; version=2"
PROTOBUF_ENVELOPE_V3_CONTENT_TYPE = "application/x-protobuf; message=ApmBatchEnvelope; version=3"
SUPPORTED_CONTENT_TYPES = frozenset({LINE_CONTENT_TYPE, PROTOBUF_CONTENT_TYPE})
GZIP_CONTENT_ENCODING = "gzip"

SDK_NAME = "android-apm"
V2_BATCH_ID_PREFIX = "b2-"
V2_BATCH_ID_HASH_BYTES = 16
V3_BATCH_ID_PREFIX = "b3-"
V3_BATCH_ID_HASH_BYTES = 16

INSTALLATION_HMAC_DOMAIN = b"androidapm:installation:v1"

PROTOBUF_LENGTH_BYTES = 4
MAX_EVENT_ID_BYTES = 128
MAX_IDENTIFIER_BYTES = 256
MAX_MAP_ENTRIES = 256
MAX_MAP_KEY_BYTES = 128
MAX_MAP_VALUE_BYTES = 8_192
MAX_EVENT_JSON_BYTES = 256 * 1_024
MAX_FUTURE_SKEW_SECONDS = 10 * 60

RETRY_AFTER_MAX_SECONDS = 60
DEFAULT_RETRY_AFTER_SECONDS = 5
MAX_EXPORT_ERROR_LENGTH = 2_048

INBOX_STATUS_PENDING = "pending"
INBOX_STATUS_PROCESSING = "processing"
INBOX_STATUS_DELIVERED = "delivered"
INBOX_STATUS_DEAD_LETTER = "dead_letter"
INBOX_STATUS_AWAITING_SYMBOLS = "awaiting_symbols"

CI_SCOPE_ARTIFACT_WRITE = "artifact:write"

ARTIFACT_TYPE_JAVA_MAPPING = "java_mapping"
ARTIFACT_TYPE_NATIVE_ELF = "native_elf"
ARTIFACT_STATUS_ACTIVE = "active"

SYMBOL_JOB_JAVA = "java"
SYMBOL_JOB_NATIVE = "native"
SYMBOL_STATUS_PENDING = "pending"
SYMBOL_STATUS_PROCESSING = "processing"
SYMBOL_STATUS_SYMBOLIZED = "symbolized"
SYMBOL_STATUS_PARTIALLY_SYMBOLIZED = "partially_symbolized"
SYMBOL_STATUS_SYMBOLS_MISSING = "symbols_missing"
SYMBOL_STATUS_METADATA_MISSING = "metadata_missing"
SYMBOL_STATUS_DISABLED = "disabled"
SYMBOL_STATUS_FAILED = "failed"

IDENTITY_QUALITY_AUTHENTICATED = "AUTHENTICATED"
IDENTITY_QUALITY_ABSENT = "ABSENT"
TIMESTAMP_QUALITY_EVENT_DECLARED = "EVENT_DECLARED"
NORMALIZATION_VERSION = 2
OTLP_INT64_MIN = -(2**63)
OTLP_INT64_MAX = 2**63 - 1

QUERY_ROLE_VIEWER = "viewer"
QUERY_ROLE_INVESTIGATOR = "investigator"
QUERY_ROLES = frozenset({QUERY_ROLE_VIEWER, QUERY_ROLE_INVESTIGATOR})

QUERY_STATE_PRESENT = "PRESENT"
QUERY_STATE_ZERO = "ZERO"
QUERY_STATE_NO_DATA = "NO_DATA"
QUERY_STATE_UNAVAILABLE = "UNAVAILABLE"
QUERY_STATE_UNKNOWN_COVERAGE = "UNKNOWN_COVERAGE"
QUERY_STATE_DEGRADED = "DEGRADED"
QUERY_STATE_LATE = "LATE"

QUERY_DECISION_CONTINUE = "continue"
QUERY_DECISION_PAUSE = "pause"
QUERY_DECISION_ROLLBACK = "rollback"
QUERY_RELEASE_DECISIONS = frozenset(
    {QUERY_DECISION_CONTINUE, QUERY_DECISION_PAUSE, QUERY_DECISION_ROLLBACK}
)

QUERY_RAW_PURPOSES = frozenset(
    {
        "incident_diagnosis",
        "release_validation",
        "customer_support",
        "security_investigation",
    }
)
