"""Protocol and runtime constants shared across the server."""

from __future__ import annotations

HEADER_SCHEMA_VERSION = "X-APM-Schema-Version"
HEADER_APP_ID = "X-APM-App-Id"
HEADER_ENVIRONMENT = "X-APM-Environment"
HEADER_SDK_VERSION = "X-APM-SDK-Version"
HEADER_APP_VERSION = "X-APM-App-Version"
HEADER_APP_BUILD = "X-APM-App-Build"
HEADER_REQUEST_ID = "X-Request-Id"
HEADER_INSTALLATION_ID = "X-APM-Installation-Id"

SCHEMA_VERSION_V1 = "1"
SUPPORTED_SCHEMA_VERSIONS = frozenset({SCHEMA_VERSION_V1})

LINE_CONTENT_TYPE = "text/plain"
PROTOBUF_CONTENT_TYPE = "application/x-protobuf"
SUPPORTED_CONTENT_TYPES = frozenset({LINE_CONTENT_TYPE, PROTOBUF_CONTENT_TYPE})
GZIP_CONTENT_ENCODING = "gzip"

PROTOBUF_LENGTH_BYTES = 4
MAX_EVENT_ID_BYTES = 128
MAX_IDENTIFIER_BYTES = 256
MAX_MAP_ENTRIES = 256
MAX_MAP_KEY_BYTES = 128
MAX_MAP_VALUE_BYTES = 8_192
MAX_EVENT_JSON_BYTES = 256 * 1_024
MAX_FUTURE_SKEW_SECONDS = 10 * 60

RETRY_AFTER_MAX_SECONDS = 60
DEFAULT_RETRY_AFTER_SECONDS = 5
MAX_EXPORT_ERROR_LENGTH = 2_048

INBOX_STATUS_PENDING = "pending"
INBOX_STATUS_PROCESSING = "processing"
INBOX_STATUS_DELIVERED = "delivered"
INBOX_STATUS_DEAD_LETTER = "dead_letter"
